[versions]

groovy = "3.0.9"
kord-extensions = "1.5.1-SNAPSHOT"
logging = "2.1.21"
logback = "1.2.8"

[libraries]
groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kord-phishing = { module = "com.kotlindiscord.kord.extensions:extra-phishing", version.ref = "kord-extensions" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.microutils:kotlin-logging", version.ref = "logging" }